env:
  global:
    - CC_TEST_REPORTER_ID=O++b7ILsnWTXTmapwAagj3YYfP7QBa5BkV5pL12tKatHbHLuRsIb7mB34GGNTM0HeP+rrJBfZR19Rp8XkWMzHOn894AurbpIGYEBr3j95Zcy5DTF32u8gX2LCk8yjrxcPsp5LnvBIqZn+N3i0063xGTCWvRLZNsjjYVm7bHdTkk4ynlqxgkhArzAS4k+y94HRTPXsb2evQFFK/h0TOIvilU5Mk/TruGD+GQGcV7qLoSgmj0hcACgF238cl85mrknuc7rYi+9s/hzwc2FMCTqrFagrPY4Y0iACaRQgKx4SaYHdOtRR0J8kqS0dHCb4SZgyFI0j9Okc84fsjqi4UwpwrobeOnwDi4C+fedTAkRoDg3EKdiOnolAU7Q8wsdpFUmMIxjFqvVbpPvmqTRlNYBa6Rr3FX3xbiSoSZYZa/KKhf9aDLdmFHxnEbFI/zdelC2xHEnqowfA6znuAHpYEF13ETYAcG/vN3WT1UMxV1gjfhKDEhhN73jtxP7b8m47XNqCEjGLDF7a8u44rIv85JWSqlSOhhdk8W8HLCAlyCm6JGArx+ic/iZ/RIqbaDG+rnZRVHCngMxZKyTwyVcF3NO+VPGChJC7OXZV+T/sDEnfzr3r+sPcbPjidg6sEdQRwB0mSmJNUQdVtBhbXv7oU7rU27y/hT8BpKh0Mo8qkuyiXI=
language: php
php:
- '7.1'
install:
- composer self-update
- make install
script: make lint test
after_script:
- vendor/bin/test-reporter
